### ISSUE TITLE
SSID Info not available

### ISSUE THREAD

**Issue by tejaskumark** [ehemmete/NetworkView#5]
Hi @ehemmete , Thanks for this work. I tried to use this work and it looks like SSID info is not available on below OS version may be due to recent location permission changes added my Apple. 
ProductName:		macOS
ProductVersion:		14.2.1

**Comment by tejaskumark** [comment]
@ehemmete Sorry to bump it early, after sometime SSID name came up. So not an issue on your side. I am trying to get SSID info, but my project is in golang and I am using objective-C through CGO. Somehow I am getting null SSID, will you be able to help on that one may be? 
Thanks.

**Comment by ehemmete** [comment]
I don't have any go experience, but my first thought is that you will still need location services to be enabled for your app.  I'm not sure how you would do that for go, but that is where I would focus.

**Comment by tejaskumark** [comment]
Actually my go code is able to get correct latitude and longitude after running it, but SSID info still remains null. It has to do with plist or I have to run something in foreground UI that part is not able to figure it out. Thanks for the update.
